# File autogenerated from Ensembl REST API. Do not edit.
data = {
    "assembly_accession": "GCA_000005005.6",
    "assembly_name": "B73 RefGen_v4",
    "chromosomes": {
        "1": {"length": 307041717, "synonyms": []},
        "2": {"length": 244442276, "synonyms": []},
        "3": {"length": 235667834, "synonyms": []},
        "4": {"length": 246994605, "synonyms": []},
        "5": {"length": 223902240, "synonyms": []},
        "6": {"length": 174033170, "synonyms": []},
        "7": {"length": 182381542, "synonyms": []},
        "8": {"length": 181122637, "synonyms": []},
        "9": {"length": 159769782, "synonyms": []},
        "10": {"length": 150982314, "synonyms": []},
        "Pt": {"length": 140384, "synonyms": []},
        "Mt": {"length": 569630, "synonyms": []},
    },
}
